### ISSUE TITLE
Seeking beyond track boundaries panics

### ISSUE THREAD

**Issue by sputnick1124** [Rigellute/spotify-tui#123]
# Summary
When trying to seek backward beyond the beginning of a song, or after the end of a song, the app crashes, but for two different reasons.

## Backward seek:
```
thread '<unnamed>' panicked at 'attempt to subtract with overflow', src/app.rs:425:19
stack backtrace:
   0: spt::panic_hook
             at src/main.rs:97
   1: spt::main::{{closure}}
             at src/main.rs:111
   2: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:478
   3: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   4: rust_begin_unwind
             at src/libstd/panicking.rs:308
   5: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   6: core::panicking::panic
             at src/libcore/panicking.rs:49
   7: spt::app::App::seek_backwards
             at src/app.rs:425
   8: spt::handlers::handle_app
             at src/handlers/mod.rs:75
   9: spt::main
             at src/main.rs:252
  10: std::rt::lang_start::{{closure}}
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/rt.rs:64
  11: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:49
      std::panicking::try::do_call
             at src/libstd/panicking.rs:293
  12: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:85
  13: std::panicking::try
             at src/libstd/panicking.rs:272
      std::panic::catch_unwind
             at src/libstd/panic.rs:394
      std::rt::lang_start_internal
             at src/libstd/rt.rs:48
  14: std::rt::lang_start
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/rt.rs:64
  15: main
  16: __libc_start_main
  17: _start
```

### Cause:
The math done here will panic if the track progress is less than 5 seconds. https://github.com/Rigellute/spotify-tui/blob/06d7b91164f0640dbdf770113f623ec8aea5f4f2/src/app.rs#L425

## Forward seek
```
thread '<unnamed>' panicked at 'Percentage should be between 0 and 100 inclusively.', /home/nick/.cargo/registry/src/github.com-1ecc6299db9ec823/tui-0.6.2/src/widgets/gauge.rs:47:9
stack backtrace:
   0: spt::panic_hook
             at src/main.rs:97
   1: spt::main::{{closure}}
             at src/main.rs:111
   2: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:478
   3: std::panicking::begin_panic
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/panicking.rs:408
   4: tui::widgets::gauge::Gauge::percent
             at /home/nick/.cargo/registry/src/github.com-1ecc6299db9ec823/tui-0.6.2/src/widgets/gauge.rs:47
   5: spt::ui::draw_playbar
             at src/ui/mod.rs:677
   6: spt::ui::draw_main_layout
             at src/ui/mod.rs:161
   7: spt::main::{{closure}}
             at src/main.rs:192
   8: tui::terminal::Terminal<B>::draw
             at /home/nick/.cargo/registry/src/github.com-1ecc6299db9ec823/tui-0.6.2/src/terminal.rs:140
   9: spt::main
             at src/main.rs:181
  10: std::rt::lang_start::{{closure}}
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/rt.rs:64
  11: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:49
      std::panicking::try::do_call
             at src/libstd/panicking.rs:293
  12: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:85
  13: std::panicking::try
             at src/libstd/panicking.rs:272
      std::panic::catch_unwind
             at src/libstd/panic.rs:394
      std::rt::lang_start_internal
             at src/libstd/rt.rs:48
  14: std::rt::lang_start
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/rt.rs:64
  15: main
  16: __libc_start_main
  17: _start
```

### Cause
If someone manages to mash the seek forward key enough (I only tried because I was curious what would happen after finding the seek backwards bug :smile: ), then the math done https://github.com/Rigellute/spotify-tui/blob/06d7b91164f0640dbdf770113f623ec8aea5f4f2/src/ui/mod.rs#L675 will manage to produce a number bigger than 100%, which triggers a false assert in tui-rs as it tries to draw a Guage larger than possible [here](https://github.com/fdehau/tui-rs/blob/b079d4da4c0316ae2d3b2d9d59182c2c1f353508/src/widgets/gauge.rs#L46-L53).

**Comment by sputnick1124** [comment]
I think both bugs are pretty easy to fix: simply check to see if there is enough track to seek to before seeking.

The only question I have is what behavior would be least surprising in response to either action. Here are my proposals:

| User Action | Expected Behavior |
| -------------- | ------------------------ |
| User tries to seek backwards while only less than 5 seconds into the track | Track progress simply resets to 0 |
| User tries to seek forward with less than 5 seconds remaining in the track | Playback jumps to the next track |

**Comment by Rigellute** [comment]
Thanks for debugging this. I think your proposals are good and we should have that behaviour. Looking at your PR now.

**Comment by sputnick1124** [comment]
Thanks for making this app! I absolutely love it and it fills a much needed gap in my day-to-day. Glad I can help out here and there.

**Comment by Rigellute** [comment]
So great to hear!
